# format = '$directory$kubernetes$all$character'
# format = '$directory$all$character'

[time]
disabled = false
format = 'ğŸ•™[\[$time\]]($style) '
time_format = "%T"

# [kubernetes]
# format = 'on [â›µ $context \($namespace\)](green) '
# disabled = false
# contexts = [
#   { context_pattern = "homelab", symbol = "ğŸ ï¸ " },
# ]
