[pyprland]
plugins = [
  "scratchpads",
]

[scratchpads.term]
animation = "fromTop"
command = "alacritty --class alacritty-dropterm"
class = "alacritty-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50
lazy = true

[scratchpads.files]
animation = "fromBottom"
command = "alacritty --class alacritty-filemanager -e yazi"
class = "alacritty-filemanager"
size = "85% 60%"
max_size = "1920px 100%"
margin = 50
lazy = true

[scratchpads.pass]
animation = "fromRight"
command = "proton-pass"
class = "Proton Pass"
size = "85% 85%"
max_size = "1920px 100%"
margin = 50
lazy = true

# [scratchpads.notes]
# command = "subl3"
# match_by = "class"
# class = "sublime_text"
# size = "60% 60%"
# lazy = true
# force_monitor = "eDP-1"
